# Generated by Django 5.0.6 on 2024-06-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipos_trabajo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='redes_sociales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
