# Generated by Django 5.0.6 on 2024-06-02 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_tipos_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='fecha_envio',
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_eventos/'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
