# Generated by Django 5.0.6 on 2024-06-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_trabajo_fecha_envio_alter_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipos_trabajo',
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipos_trabajo',
            field=models.ManyToManyField(blank=True, to='eventos.tipoevento'),
        ),
    ]
