# Generated by Django 5.0.6 on 2024-06-03 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_rename_tipoevento_tipotrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='revisores',
            field=models.ManyToManyField(blank=True, related_name='eventos_revisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
