# Generated by Django 5.0.6 on 2024-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_revisores_trabajo_estado_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='revisores',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='estado_revision',
        ),
        migrations.AlterField(
            model_name='revision',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
