# Generated by Django 5.0.6 on 2024-06-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_sitio_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='ubicacion',
        ),
    ]
